# Compêdio de pesquisa


## Definição
Um compêndio (do inglês, compendium) pode ser [definido](https://www.priberam.pt/dlpo/compêndio) como uma compilação em que se encontra resumido o mais indispensável de um estudo. O termo "research compendium" foi cunhado em meados dos anos 2000 em uma publicação sobre pesquisa reproduzível com enfoque em análise estatística.

> We introduce the concept of a compendium as both a container for the different elements that make up the document and its computations (i.e. text, code, data, ...), and as a means for distributing, managing and updating the collection.[@Robert_Gentleman_Department_of_Biostatistics_Harvard_University2004-qt]

Na visão dos autores, o compêndio tem como base um ou mais documentos dinâmicos, a partir dos quais são gerados os demais documentos estáticos como um PDF a partir de um arquivo TEX (há mais de 10 anos o TEX era o equivalente ao Markdown). Também, esses documentos dinâmicos (e seus elementos de texto, código e dados) devem ser facilmente extraídos e processados de diferentes maneiras pelo autor e pelos leitores.

Portanto, é importante que um compêndio da pesquisa seja desenvolvido de maneira padronizada para que outros pesquisadores, de forma facilitada, possam inspecionar, reproduzir e ampliar a pesquisa. Os princípios básicos para a confecção de um compêndio de pesquisa são:

1) Organização segundo a convenção criada pela academia
2) Separação clara de dados, códigos e saídas
3) Especificação do ambiente computacional
4) Documentação detalhada de cada elemento e rotina

Um dos objetivo de se criar um compêndio de pesquisa é, em primeira instância, facilitar o trabalho do pesquisador e permitir que ele distribua os produtos gerados pela pesquisa de uma maneira mais ampla possível, visando a dar visibilidade ao trabalho. Além disso, a eficiência do trabalho é aumentada com a incorporação de uma sistemática que pode ser replicada em outros projetos, dimuindo assim os custos operacionais e acelerando o trabalho. Tem se discutido que publicações que são acompanhas de um compêndio tendem a receber maior atenção, credibilidade e citações uma vez que o compendio é um tipo de publicação por si só. Imagine o quanto pode ser útil tornar o compêndio público antes da submissão do trabalho de forma que editores e revisores possam revisar os dados e os métodos (estatísticos principalmente) que foram utilizados, entender as decisões tomadas no processo analítico e os resultados obticos. Alem disso, uma vez que o compêndio é publicado, os autores poderão receber comentários dos pares e dos revisores para melhorar o trabalho como um todo.

Antes de falarmos sobre como organizar o compêndio de pesquisa, veremos aspectos e cuidados específicos de organização dos dados.

## Dados

Segundo Wilkinson et al. (2016), os dados devem ser organizados segundo o princípio **FAIR** = **F**indable, **A**ccessible, **I**nteroperable and **R**eusable. 

Compartilhar os dados (o que pode ser aplicado também aos códigos, significa facilitar a distribuição e o acesso pela comunidade científica, ou seja que eles sejam facilmente **encontrados** e **acessados**. Qual a vantagem disso? reproduzir os resultados originais e pertimitir que novas análises sejam feitas usando os mesmos dados, ou mesmo combinando com outros conjuntos de dados (metanálise). É importante que os dados estejam em um formato que seja de fácil entendimento para facilitar o uso. Três boas práticas são recomendadas:
 
1. Documentação: dados bem documentados e descritos (metadados) são mais fáceis de entender
2. Formataçao: dados formatados apropriadamente podem ser usados em diversos programas de computador
3. Distribuição: depósito em repositórios conhecidos e com licença aberta facilita que sejam encontrados e reusados

Práticas de compartilhamento de dados talvez ainda não sejam valorizadas pela maioria dos pesquisadores, haja visto que a maioria dos trabalhos ainda não disponibilizam os dados originais. As vantagens óbvias seria a reprodução e possível melhorias na análise, o reuso dos dados em metanálises para chegar a conclusões gerais e gerar novo conhecimento que só é possível com dados compartilhados em larga escala. Mas por que ainda os pesquisadores não compartilham os dados? os motivos podem ser ligados ao receio de perder uma competição por publicações ou mesmo a falta de conhecimento sobre como fazer o compartilhamento. A percepção que domina é que organizar e depositar dados é difícil tecnicamente ou leva muito tempo,


## Formato


## Planilhas eletronicas


## Nomes

## Copias

## Formato

## Depósito

## Licença
